import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";

const currentDate = new Date().toLocaleString();

export const generateFullReportPDF = (reports) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const addHeader = () => {
    doc.setFont("Times", "bold");
    doc.setFontSize(14);
    doc.setTextColor(4, 4, 252);

    doc.text("EAST AFRICAN COMMUNITY", pageWidth / 2, 15, { align: "center" });
    doc.text("SECRETARIAT", pageWidth / 2, 21, { align: "center" });

    // Logo
    const logoWidth = 32;
    const logoHeight = 28;
    const logoX = (pageWidth - logoWidth) / 2;
    doc.addImage(logo, "PNG", logoX, 22, logoWidth, logoHeight);

    // Contact details
    doc.setFontSize(8);
    doc.setFont("Times", "normal");
    doc.setTextColor(13, 13, 13);

    // Left side
    doc.text("EAC Close, Afrika Mashariki Road,", 30, 33);
    doc.text("P.O. Box 1096", 30, 37);
    doc.text("ARUSHA, TANZANIA", 30, 41);

    // Right side
    doc.text("Tel: +255-27-2504253/8", pageWidth - 35, 33, { align: "right" });
    doc.text("Fax: +255-27-2504255/2504481", pageWidth - 35, 37, {
      align: "right",
    });
    doc.text("Email: eac@eachq.org", pageWidth - 35, 41, { align: "right" });
    doc.text("Web: http://www.eac.int", pageWidth - 35, 45, { align: "right" });

    // Report title
    doc.setFontSize(12);
    doc.setFont("Times", "bold");
    doc.setTextColor(83, 83, 83);
    doc.text("Internship Programme Reports", pageWidth / 2, 58, {
      align: "center",
    });

    // Header line
    doc.setDrawColor(12, 115, 38);
    doc.setLineWidth(0.7);
    doc.line(15, 62, pageWidth - 15, 62);
  };

  const addFooter = () => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(100);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 8, {
        align: "right",
      });
      doc.text("Generated by Internship Management System", 20, pageHeight - 8);
    }
  };

  // Add header
  addHeader();

  // Add generation date
  doc.setFontSize(7);
  doc.setTextColor(13, 13, 13);
  doc.text(`Date Generated: ${currentDate}`, pageWidth - 15, 66, {
    align: "right",
  });

  // Prepare table data
  const tableRows = reports.map((report, index) => [
    index + 1,
    `${report.surname || ""} ${report.firstName || ""} ${
      report.otherNames || ""
    }`,
    report.internshipDepartment || "N/A",
    report.internshipSupervisor || "N/A",
    report.internshipStartDate
      ? new Date(report.internshipStartDate).toLocaleDateString()
      : "N/A",
    report.internshipEndDate
      ? new Date(report.internshipEndDate).toLocaleDateString()
      : "N/A",
    report.status || "N/A",
  ]);

  // Add table
  autoTable(doc, {
    head: [
      [
        "#",
        "Name",
        "Department",
        "Supervisor",
        "Start Date",
        "End Date",
        "Status",
      ],
    ],
    body: tableRows,
    startY: 70,
    theme: "striped",
    headStyles: {
      fillColor: [12, 115, 38],
      textColor: [255, 255, 255],
      fontSize: 9,
      halign: "start",
    },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    pageBreak: "auto",
  });

  // Add footer
  addFooter();

  // Save PDF
  doc.save("internship_full_report.pdf");
};

export const generateReportPDF = (report) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const addHeader = () => {
    doc.setFont("Times", "bold");
    doc.setFontSize(14);
    doc.setTextColor(4, 4, 252);

    doc.text("EAST AFRICAN COMMUNITY", pageWidth / 2, 15, { align: "center" });
    doc.text("SECRETARIAT", pageWidth / 2, 21, { align: "center" });

    // Logo
    const logoWidth = 32;
    const logoHeight = 28;
    const logoX = (pageWidth - logoWidth) / 2;
    doc.addImage(logo, "PNG", logoX, 22, logoWidth, logoHeight);

    // Contact details
    doc.setFontSize(8);
    doc.setFont("Times", "normal");
    doc.setTextColor(13, 13, 13);

    // Left side
    doc.text("EAC Close, Afrika Mashariki Road,", 30, 33);
    doc.text("P.O. Box 1096", 30, 37);
    doc.text("ARUSHA, TANZANIA", 30, 41);

    // Right side
    doc.text("Tel: +255-27-2504253/8", pageWidth - 35, 33, { align: "right" });
    doc.text("Fax: +255-27-2504255/2504481", pageWidth - 35, 37, {
      align: "right",
    });
    doc.text("Email: eac@eachq.org", pageWidth - 35, 41, { align: "right" });
    doc.text("Web: http://www.eac.int", pageWidth - 35, 45, { align: "right" });

    // Report title
    doc.setFontSize(12);
    doc.setFont("Times", "bold");
    doc.setTextColor(83, 83, 83);
    doc.text("Internship Programme Reports", pageWidth / 2, 58, {
      align: "center",
    });

    // Header line
    doc.setDrawColor(12, 115, 38);
    doc.setLineWidth(0.7);
    doc.line(15, 62, pageWidth - 15, 62);
  };

  addHeader();

  // Add individual report content
  doc.setFontSize(7);
  doc.setTextColor(13, 13, 13);
  doc.text(`Date Generated: ${currentDate}`, pageWidth - 15, 66, {
    align: "right",
  });

  doc.setFont("Times", "bold");
  doc.setFontSize(14);
  doc.text("Internship Applicant Information", 20, 70);

  // Details section
  const details = [
    {
      label: "Name:",
      value: `${report.surname || ""} ${report.firstName || ""} ${
        report.otherNames || ""
      }`,
    },
    { label: "Department:", value: report.internshipDepartment || "N/A" },
    { label: "Supervisor:", value: report.internshipSupervisor || "N/A" },
    { label: "Email:", value: report.email || "N/A" },
    { label: "Phone:", value: report.phoneNumber || "N/A" },
    {
      label: "Start Date:",
      value: report.internshipStartDate
        ? new Date(report.internshipStartDate).toLocaleDateString()
        : "N/A",
    },
    {
      label: "End Date:",
      value: report.internshipEndDate
        ? new Date(report.internshipEndDate).toLocaleDateString()
        : "N/A",
    },
    { label: "Status:", value: report.status || "N/A" },
  ];

  let currentY = 79;
  const lineHeight = 10;

  details.forEach(({ label, value }) => {
    doc.setFont("Times", "bold");
    doc.text(label, 30, currentY);
    doc.setFont("Times", "normal");
    doc.text(String(value), 90, currentY);
    currentY += lineHeight;
  });

  // Add footer
  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text("Generated by Internship Management System", 20, pageHeight - 8);
  doc.text("Page 1", pageWidth - 20, pageHeight - 8, { align: "right" });

  // Save PDF
  doc.save(`${report.surname}_${report.firstName}_internship_report.pdf`);
};
